### ISSUE TITLE
Error with logging in.

### ISSUE THREAD

**Issue by skapeyi** [caleboki/acl#2]
Hey. Thanks for the awesome tutorial.
I implemented [this](https://scotch.io/tutorials/user-authorization-in-laravel-54-with-spatie-laravel-permission) for one of my projects and it worked well. I could add roles and permissions and assign them to users. 
The problem after was, I couldn't log in again. And that is for all the user accounts that could previously log in. 
When you create a new account it logs you in directly and that is fine but once you logout, that is it. I imagined I had missed something out following the tutorial and then I cloned this repo and the same thing happened.  Any Idea what this could be?

**Comment by caleboki** [comment]
Remove the bcrypt function in the create method of the RegisterController.php file. So the create method looks like this
`
protected function create(array $data)

{
    return User::create([
        'name' => $data['name'],
        'email' => $data['email'],
        'password' => $data['password'],
    ]);
} `

I have a made a new commit, fixing the error. You may clone the repo again and please let me know if there is any other issue.

**Comment by skapeyi** [comment]
Makes sense. So it was encrypting the password twice, right? It works well now for new accounts created. Their authentication works well.
However, how do you now explain old accounts not being able to login?

**Comment by caleboki** [comment]
Delete the old accounts from the database and create new ones. It should work now
